# Generated by Django 5.0.1 on 2026-07-05 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], max_length=20)),
                ('maximum_participants', models.PositiveIntegerField()),
                ('maximum_team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_marks', models.PositiveIntegerField(default=100)),
                ('number_of_judges', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Registration Open', 'Registration Open'), ('Registration Closed', 'Registration Closed'), ('Judging', 'Judging'), ('Completed', 'Completed'), ('Published', 'Published')], db_index=True, default='Draft', max_length=30)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
