# Generated by Django 6.0.6 on 2026-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(default='', max_length=255)),
                ('festival_name', models.CharField(default='', max_length=255)),
                ('academic_year', models.CharField(default='', max_length=50)),
                ('maximum_participation_limit', models.PositiveIntegerField(default=0)),
                ('maximum_group_size', models.PositiveIntegerField(default=0)),
                ('first_place_points', models.PositiveIntegerField(default=0)),
                ('second_place_points', models.PositiveIntegerField(default=0)),
                ('third_place_points', models.PositiveIntegerField(default=0)),
                ('participation_points', models.PositiveIntegerField(default=0)),
                ('maximum_marks', models.PositiveIntegerField(default=100)),
                ('judging_method', models.CharField(default='Average', max_length=20)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
